{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0 (24.06)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"FactSales\",\"DimProduct\",\"DimGeography\",\"DimProductCategory\",\"DimCustomer\",\"DimStore\",\"DimDate\",\"_Medidas\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "c799be96-b917-435d-b08e-5ca5f52e2d26",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "DateKey",
        "fromTable": "FactSales",
        "toColumn": "Datekey",
        "toTable": "DimDate"
      },
      {
        "name": "a9119f9c-6f68-49b5-b3b9-aca240daacd0",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "ProductKey",
        "fromTable": "FactSales",
        "toColumn": "ProductKey",
        "toTable": "DimProduct"
      },
      {
        "name": "20472068-2b37-48fc-bbc8-136aa4958f87",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "StoreKey",
        "fromTable": "FactSales",
        "toColumn": "StoreKey",
        "toTable": "DimStore"
      },
      {
        "name": "742bfbfb-e0bf-4fd2-9f29-2fd89343fc48",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "GeographyKey",
        "fromTable": "DimStore",
        "toColumn": "GeographyKey",
        "toTable": "DimGeography"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "FactSales",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4a8b0ee5-7465-4efa-ab4d-c0a59184cc28",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "StoreKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "283125c6-5dd5-4a9d-bba6-08c657e397e5",
            "sourceColumn": "StoreKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8a3b84eb-8928-46a2-afed-87c5937299e5",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "UnitCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "553c68f5-5cd3-4d95-8d4a-75e6652dfd01",
            "sourceColumn": "UnitCost",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "18002a1d-88fa-44de-a8c7-e6da000966cb",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "SalesQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0fac0d8f-7a8c-4c62-8946-ba58def149c7",
            "sourceColumn": "SalesQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "ReturnAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "522b8c13-ba64-434f-a452-6b1e2da4596a",
            "sourceColumn": "ReturnAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "DiscountQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f3ff0750-07e6-450d-b9db-01d917c366b9",
            "sourceColumn": "DiscountQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "DiscountAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "f272cdec-711c-44d4-ba87-22bddc5b06f7",
            "sourceColumn": "DiscountAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "20635954-84de-452b-a090-85923ede7a2d",
            "sourceColumn": "TotalCost",
            "summarizeBy": "sum"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "a4219518-abcf-4664-803b-dffb96ec26d0",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "7f0c0d18-b0e6-48b1-9cfb-b34eb03c3662",
        "partitions": [
          {
            "name": "FactSales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"DESKTOP-18PC6B5\"),",
                "    ContosoRetailDW = Fonte{[Name=\"ContosoRetailDW\"]}[Data],",
                "    dbo_FactSales = ContosoRetailDW{[Schema=\"dbo\",Item=\"FactSales\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(dbo_FactSales,{{\"DateKey\", type date}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"SalesKey\", \"channelKey\", \"PromotionKey\", \"CurrencyKey\", \"ReturnQuantity\", \"ETLLoadID\", \"LoadDate\", \"UpdateDate\", \"DimChannel\", \"DimCurrency\", \"DimDate\", \"DimProduct\", \"DimPromotion\", \"DimStore\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimProduct",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e4cdfbb9-df03-4710-85df-efea7e3fe51c",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductLabel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8690770-5186-4f6a-ae0d-500a658002eb",
            "sourceColumn": "ProductLabel",
            "summarizeBy": "none"
          },
          {
            "name": "ProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e1845eb-2eae-42ac-895f-f1907206958b",
            "sourceColumn": "ProductName",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "016500ac-baec-42d4-a389-00fbc80fc387",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "BrandName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb340089-3c5b-4339-85be-8a791d6b21ee",
            "sourceColumn": "BrandName",
            "summarizeBy": "none"
          },
          {
            "name": "ClassID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5fa9ee0-4c9b-4119-af93-0a9000be9930",
            "sourceColumn": "ClassID",
            "summarizeBy": "none"
          },
          {
            "name": "ClassName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0416c3c3-49d1-4cd0-af92-fce1b6deb089",
            "sourceColumn": "ClassName",
            "summarizeBy": "none"
          },
          {
            "name": "ColorName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d8fd9e0-f7e0-4faf-be7d-3f79b3f1bfc5",
            "sourceColumn": "ColorName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "dcfc64e1-1e41-49c9-bfbc-6cc320043be1",
        "partitions": [
          {
            "name": "DimProduct",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"DESKTOP-18PC6B5\"),",
                "    ContosoRetailDW = Fonte{[Name=\"ContosoRetailDW\"]}[Data],",
                "    dbo_DimProduct = ContosoRetailDW{[Schema=\"dbo\",Item=\"DimProduct\"]}[Data],",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(dbo_DimProduct,{ \"ProductDescription\", \"Manufacturer\", \"StyleID\", \"StyleName\", \"ColorID\", \"Size\", \"SizeRange\", \"SizeUnitMeasureID\", \"Weight\", \"ImageURL\", \"ProductURL\", \"ETLLoadID\", \"LoadDate\", \"UpdateDate\", \"DimProductSubcategory\", \"FactInventory\", \"FactOnlineSales\", \"FactSales\", \"FactSalesQuota\", \"WeightUnitMeasureID\", \"UnitOfMeasureID\", \"UnitOfMeasureName\", \"StockTypeID\", \"StockTypeName\", \"UnitCost\", \"UnitPrice\", \"AvailableForSaleDate\", \"StopSaleDate\", \"Status\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimGeography",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "GeographyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d2453e0a-0946-42e5-a479-d906255fb60b",
            "sourceColumn": "GeographyKey",
            "summarizeBy": "none"
          },
          {
            "name": "GeographyType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cbc00a8a-51e1-4a79-a3b0-ffbff35606a4",
            "sourceColumn": "GeographyType",
            "summarizeBy": "none"
          },
          {
            "name": "ContinentName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2250af7e-4441-4754-8dc3-d0e695aae2b1",
            "sourceColumn": "ContinentName",
            "summarizeBy": "none"
          },
          {
            "name": "CityName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73dafe53-49d6-4fd5-bd59-de8f11ebe00b",
            "sourceColumn": "CityName",
            "summarizeBy": "none"
          },
          {
            "name": "RegionCountryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1edb2412-83a8-4f2c-a8c2-d02039a71bac",
            "sourceColumn": "RegionCountryName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "10263e77-cdbb-441e-822e-3fb45076b4cf",
        "partitions": [
          {
            "name": "DimGeography",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"DESKTOP-18PC6B5\"),",
                "    ContosoRetailDW = Fonte{[Name=\"ContosoRetailDW\"]}[Data],",
                "    dbo_DimGeography = ContosoRetailDW{[Schema=\"dbo\",Item=\"DimGeography\"]}[Data],",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(dbo_DimGeography,{\"GeographyKey\", \"GeographyType\", \"ContinentName\", \"CityName\", \"StateProvinceName\", \"RegionCountryName\", \"Geometry\", \"ETLLoadID\"}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Outras Colunas Removidas\",{\"StateProvinceName\", \"Geometry\", \"ETLLoadID\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimProductCategory",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e03135ce-2e4b-46e2-9cfd-08776a71d3c7",
            "sourceColumn": "ProductCategoryKey",
            "summarizeBy": "count"
          },
          {
            "name": "ProductCategoryLabel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38fd4e01-9481-4d1c-9705-98443767cbea",
            "sourceColumn": "ProductCategoryLabel",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCategoryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb4c0801-e62c-448c-ab8e-45300ec23704",
            "sourceColumn": "ProductCategoryName",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCategoryDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ea293fb-5e20-4f4f-8582-c2e36e601d11",
            "sourceColumn": "ProductCategoryDescription",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "dde43938-1918-4d52-8844-7ecb421f4539",
        "partitions": [
          {
            "name": "DimProductCategory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"DESKTOP-18PC6B5\"),",
                "    ContosoRetailDW = Fonte{[Name=\"ContosoRetailDW\"]}[Data],",
                "    dbo_DimProductCategory = ContosoRetailDW{[Schema=\"dbo\",Item=\"DimProductCategory\"]}[Data],",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(dbo_DimProductCategory,{\"ProductCategoryKey\", \"ProductCategoryLabel\", \"ProductCategoryName\", \"ProductCategoryDescription\"})",
                "in",
                "    #\"Outras Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimCustomer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f5815ac8-35cd-4c39-b967-a4fa46a71130",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "count"
          },
          {
            "name": "GeographyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f9b3ebff-2f77-4255-8102-340e06e2bbda",
            "sourceColumn": "GeographyKey",
            "summarizeBy": "count"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d3aad8d-6e4a-4f0d-8630-360f804f48dd",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6aa998dd-d75d-4e0b-a02c-f79487713b58",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "BirthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8da98ec2-b9bd-4792-9a9e-a50c75fdb6c6",
            "sourceColumn": "BirthDate",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3fad7e31-9447-4a7c-8c18-982678dde63a",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "YearlyIncome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "2bbcb50b-2ba2-4db5-a93d-4cf630122019",
            "sourceColumn": "YearlyIncome",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "3e36e4bf-2921-42ed-a871-079bec156a16",
        "partitions": [
          {
            "name": "DimCustomer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"DESKTOP-18PC6B5\"),",
                "    ContosoRetailDW = Fonte{[Name=\"ContosoRetailDW\"]}[Data],",
                "    dbo_DimCustomer = ContosoRetailDW{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data],",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(dbo_DimCustomer,{\"CustomerKey\", \"GeographyKey\", \"CustomerLabel\", \"Title\", \"FirstName\", \"MiddleName\", \"LastName\", \"NameStyle\", \"BirthDate\", \"MaritalStatus\", \"Suffix\", \"Gender\", \"EmailAddress\", \"YearlyIncome\", \"TotalChildren\", \"NumberChildrenAtHome\", \"Education\", \"Occupation\", \"HouseOwnerFlag\", \"NumberCarsOwned\", \"AddressLine1\", \"AddressLine2\", \"Phone\", \"DateFirstPurchase\", \"CustomerType\", \"CompanyName\"}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Outras Colunas Removidas\",{\"Title\", \"MiddleName\", \"NameStyle\", \"MaritalStatus\", \"Suffix\", \"EmailAddress\", \"TotalChildren\", \"NumberChildrenAtHome\", \"Education\", \"Occupation\", \"AddressLine1\", \"AddressLine2\", \"Phone\", \"DateFirstPurchase\", \"CustomerType\", \"CompanyName\", \"NumberCarsOwned\", \"HouseOwnerFlag\", \"CustomerLabel\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimStore",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "StoreKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e76ac117-e117-42fa-a103-d716c1974098",
            "sourceColumn": "StoreKey",
            "summarizeBy": "none"
          },
          {
            "name": "GeographyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e437bf5c-13c8-4217-ae86-c0fcf8aead82",
            "sourceColumn": "GeographyKey",
            "summarizeBy": "none"
          },
          {
            "name": "StoreType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6cb45a9-e93c-4442-8f13-a90f0ceb50b1",
            "sourceColumn": "StoreType",
            "summarizeBy": "none"
          },
          {
            "name": "StoreName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7008c58-6800-47f3-b1e8-4c9805606e74",
            "sourceColumn": "StoreName",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ce987e4-3687-456b-ac3f-22e36275a37e",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5e367931-a9d4-4620-a48c-af3668b47d62",
        "partitions": [
          {
            "name": "DimStore",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"DESKTOP-18PC6B5\"),",
                "    ContosoRetailDW = Fonte{[Name=\"ContosoRetailDW\"]}[Data],",
                "    dbo_DimStore = ContosoRetailDW{[Schema=\"dbo\",Item=\"DimStore\"]}[Data],",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(dbo_DimStore,{\"StoreKey\", \"GeographyKey\", \"StoreManager\", \"StoreType\", \"StoreName\", \"StoreDescription\", \"Status\", \"OpenDate\", \"CloseDate\", \"EntityKey\", \"ZipCode\", \"ZipCodeExtension\", \"StorePhone\", \"StoreFax\", \"AddressLine1\", \"AddressLine2\", \"CloseReason\", \"EmployeeCount\", \"SellingAreaSize\", \"LastRemodelDate\", \"GeoLocation\", \"Geometry\"}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Outras Colunas Removidas\",{\"StoreManager\", \"StoreDescription\", \"OpenDate\", \"CloseDate\", \"EntityKey\", \"StoreFax\", \"AddressLine1\", \"AddressLine2\", \"CloseReason\", \"EmployeeCount\", \"SellingAreaSize\", \"LastRemodelDate\", \"GeoLocation\", \"Geometry\", \"ZipCode\", \"ZipCodeExtension\", \"StorePhone\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Datekey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "cd061a94-d73b-491d-a896-e55d6c5da499",
            "sourceColumn": "Datekey",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e18fdd94-5fd8-46a6-82d5-bef7a1f01974",
            "sourceColumn": "CalendarYear",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarQuarterLabel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a4237f6-5b32-4749-971b-584b15e9ca65",
            "sourceColumn": "CalendarQuarterLabel",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarMonthLabel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "875f58fb-de36-4953-b008-a8a28a853107",
            "sortByColumn": "Month",
            "sourceColumn": "CalendarMonthLabel",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH(DimDate[Datekey])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b5bd7cff-1d8c-4160-93f9-05c70ad5bee9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "7d8513f3-9f9c-4cc8-911e-d9a5c4591034",
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Databases(\"DESKTOP-18PC6B5\"),",
                "    ContosoRetailDW = Fonte{[Name=\"ContosoRetailDW\"]}[Data],",
                "    dbo_DimDate = ContosoRetailDW{[Schema=\"dbo\",Item=\"DimDate\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(dbo_DimDate,{{\"Datekey\", type date}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"FullDateLabel\", \"DateDescription\", \"CalendarYearLabel\", \"CalendarHalfYear\", \"CalendarHalfYearLabel\", \"CalendarQuarter\", \"CalendarMonth\", \"CalendarWeek\", \"CalendarDayOfWeek\", \"CalendarDayOfWeekLabel\", \"FiscalYear\", \"FiscalYearLabel\", \"FiscalHalfYear\", \"FiscalHalfYearLabel\", \"FiscalMonth\", \"FiscalMonthLabel\", \"IsWorkDay\", \"IsHoliday\", \"HolidayName\", \"EuropeSeason\", \"NorthAmericaSeason\", \"AsiaSeason\", \"FactExchangeRate\", \"FactITMachine\", \"FactITSLA\", \"FactInventory\", \"FactOnlineSales\", \"FactSales\", \"FactSalesQuota\", \"FactStrategyPlan\", \"FiscalQuarter\", \"FiscalQuarterLabel\", \"CalendarWeekLabel\"}),",
                "    #\"Primeiros caracteres extraídos\" = Table.TransformColumns(#\"Colunas Removidas\", {{\"CalendarMonthLabel\", each Text.Start(_, 3), type text}})",
                "in",
                "    #\"Primeiros caracteres extraídos\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "2983e566-a048-4aaf-ae7b-c3eb4fa3f1c3",
        "measures": [
          {
            "name": "% Lucro",
            "expression": [
              "",
              "",
              "DIVIDE(",
              "    [Faturamento] - [Lucro],",
              "    [Faturamento],",
              "    BLANK()",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "07af38eb-57ad-47a0-9f8d-c303ff7a7881"
          },
          {
            "name": "Faturamento % YoY",
            "expression": [
              "",
              "",
              "DIVIDE(",
              "    [Faturamento]-[Faturamento YoY],",
              "    [Faturamento],",
              "    BLANK()",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a6febf64-3946-4fcd-b732-39ee747efa99"
          },
          {
            "name": "Faturamento",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "",
              "SUMX(",
              "    FactSales,",
              "    FactSales[UnitPrice] * FactSales[SalesQuantity]",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "1ecbabbe-6fdc-4090-8422-ece4dad819ba"
          },
          {
            "name": "Faturamento + % YoY Txt",
            "expression": [
              "",
              "",
              "VAR CONDICIONAL = ",
              "    IF(",
              "        [Faturamento % YoY] > 0,  FORMAT([Faturamento % YoY],\"🡹 0.00%\"),",
              "        \"🡻\" & FORMAT([Faturamento % YoY],\" 0.00%\")",
              "    )",
              "        ",
              " RETURN ",
              "  CONDICIONAL & \" | \" & IF([Faturamento YoY] = BLANK(), \"Sem valores\", FORMAT([Faturamento YoY], \"R$ #,0,,,.00 Bi\"))"
            ],
            "lineageTag": "11b336f7-d2fa-4a8e-95aa-5f2890a628df"
          },
          {
            "name": "Faturamento YoY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "",
              "CALCULATE(",
              "        [Faturamento],",
              "        DATEADD(DimDate[Datekey], -1, YEAR)",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "c133cd03-da1f-4c13-aad4-dc80a16125e5"
          },
          {
            "name": "Faturamento Txt",
            "expression": [
              "",
              "",
              "\"R$ \" & FORMAT([Faturamento], \"#,0,,,.00 Bi\")"
            ],
            "lineageTag": "0831674d-0026-4dd8-ab42-0de693dbad21"
          },
          {
            "name": "Lucro",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "",
              "SUMX(",
              "    FactSales,",
              "    (FactSales[UnitPrice] - FactSales[UnitCost]) * FactSales[SalesQuantity])/10"
            ],
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "c6ee057a-fa5d-4d68-87f2-79ef618437cb"
          },
          {
            "name": "Qtd Vendas",
            "expression": "COUNTROWS(FactSales)",
            "formatString": "0",
            "lineageTag": "32a07381-643d-4579-8b82-9a336051f698"
          },
          {
            "name": "Qtd Vendas Txt",
            "expression": [
              "",
              "",
              "FORMAT([Qtd Vendas], \"#,0,,.00 Mi\")"
            ],
            "lineageTag": "4b477844-4422-4e3c-ad29-8831745d794e"
          },
          {
            "name": "Quantidade Vendida % YoY",
            "expression": [
              "",
              "",
              "DIVIDE(",
              "    [Qtd Vendas]-[Quantidade Vendida YoY],",
              "    [Qtd Vendas],",
              "    BLANK()",
              ")"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "5e2c56a7-987e-4ca6-8292-dbf9844f8713"
          },
          {
            "name": "Quantidade Vendida YoY",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "        [Qtd Vendas],",
              "        DATEADD(DimDate[Datekey], -1, YEAR)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1dc4ff2c-92cb-4c55-a99f-bdf1cd519745"
          },
          {
            "name": "Qtd Vendida + % YoY Txt",
            "expression": [
              "",
              "",
              "VAR CONDICIONAL = ",
              "    IF(",
              "        [Quantidade Vendida % YoY] > 0,  FORMAT([Quantidade Vendida % YoY],\"🡹 0.00%\"),",
              "        \"🡻\" & FORMAT([Quantidade Vendida % YoY],\" 0.00%\")",
              "    )",
              "        ",
              " RETURN ",
              "  CONDICIONAL & \" | \" & IF([Quantidade Vendida YoY] = BLANK(), \"Sem valores\", FORMAT([Quantidade Vendida YoY], \"#,0,,.00 Mi\"))"
            ],
            "lineageTag": "21ea2206-cd32-41c1-9de6-c4d5fe8352c8"
          },
          {
            "name": "Lucro Txt",
            "expression": [
              "",
              "",
              "FORMAT([Lucro], \"#,0,,.00 Mi\")"
            ],
            "lineageTag": "504dbd71-4f76-4f03-84f7-f5bfcd05052e"
          },
          {
            "name": "Lucro YoY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "",
              "CALCULATE(",
              "        [Lucro],",
              "        DATEADD(DimDate[Datekey], -1, YEAR)",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "9714d78a-d116-478d-a9f7-985ff5bc8404"
          },
          {
            "name": "Lucro + % YoY Txt",
            "expression": [
              "",
              "",
              "VAR CONDICIONAL = ",
              "    IF(",
              "        [Lucro % YoY] > 0,  FORMAT([Lucro % YoY],\"🡹 0.00%\"),",
              "        \"🡻\" & FORMAT([Lucro % YoY],\" 0.00%\")",
              "    )",
              "        ",
              " RETURN ",
              "  CONDICIONAL & \" | \" & IF([Lucro YoY] = BLANK(), \"Sem valores\", FORMAT([Lucro YoY], \"#,0,,.00 Mi\"))"
            ],
            "lineageTag": "895129fb-fd0c-4276-982a-759db1fff21c"
          },
          {
            "name": "Lucro % YoY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "DIVIDE(",
              "    [Lucro]-[Lucro YoY],",
              "    [Lucro],",
              "    BLANK()",
              ")"
            ],
            "lineageTag": "f158331e-9120-46c3-a931-e08b49349baa"
          },
          {
            "name": "Qtd produtos distintos",
            "expression": [
              "",
              "",
              "DISTINCTCOUNTNOBLANK(FactSales[ProductKey])"
            ],
            "formatString": "0",
            "lineageTag": "5e2c947b-6cd7-4864-ad78-25f7bd06ec93"
          },
          {
            "name": "Qtd produtos distintos YoY",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "        [Qtd produtos distintos],",
              "        DATEADD(DimDate[Datekey], -1, YEAR)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "8e1ff937-c77f-429e-8be9-9a0aaae9979d"
          },
          {
            "name": "Qtd produtos distintos % YoY",
            "expression": [
              "",
              "",
              "DIVIDE(",
              "    [Qtd produtos distintos]-[Qtd produtos distintos YoY],",
              "    [Qtd produtos distintos],",
              "    BLANK()",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dcc03353-b8b9-4895-a6b6-3639a668c7be"
          },
          {
            "name": "Qtd produtos dis Txt",
            "expression": [
              "",
              "",
              "FORMAT([Qtd produtos distintos], \"#,0,.00 Mil\")"
            ],
            "lineageTag": "393e086b-d7b1-46ee-949d-8b8bfdb9ab4a"
          },
          {
            "name": "Qtd produtos dis + % YoY Txt",
            "expression": [
              "",
              "",
              "VAR CONDICIONAL = ",
              "    IF(",
              "        [Qtd produtos distintos % YoY] > 0,  FORMAT([Qtd produtos distintos % YoY],\"🡹 0.00%\"),",
              "        \"🡻\" & FORMAT([Qtd produtos distintos % YoY],\" 0.00%\")",
              "    )",
              "        ",
              " RETURN ",
              "  CONDICIONAL & \" | \" & IF([Qtd produtos distintos YoY] = BLANK(), \"Sem valores\", FORMAT([Qtd produtos distintos YoY], \"#,0,.00 Mil\"))"
            ],
            "lineageTag": "7a410cea-f9e2-4578-8105-b2dd47104a15"
          }
        ],
        "partitions": [
          {
            "name": "_Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}